### ISSUE TITLE
Decoding error

### ISSUE THREAD

**Issue by dewie** [gaynetdinov/ex_marshal#5]
I'm trying to decode a rails session that is dumped with Marshal 

2.1.5 :032 > s.data.data
 => "\x04\b{\tI\"\x19warden.user.user.key\x06:\x06ET[\a[\x06I\"\x1D548814a064657654501a0000\x06;\x00TI\"\"$2a$10$73PE6lJ5iYxwumwZQ/qjjO\x06;\x00TI\"\x1Dwarden.user.user.session\x06;\x00T{\x06I\"\x16unique_session_id\x06;\x00TI\"\x19AsqZJFimQjSEsYyAgL8T\x06;\x00FI\"\nflash\x06;\x00T{\aI\"\fdiscard\x06;\x00T[\x06I\"\vnotice\x06;\x00FI\"\fflashes\x06;\x00T{\x06@\x13I\" Je bent succesvol ingelogd.\x06;\x00TI\"\x10_csrf_token\x06;\x00FI\"1aOaum1ZeInfFvRgG8srczhiGnbpx41VIdix7+4QKxzo=\x06;\x00F" 
2.1.5 :033 > Marshal.load(s.data.data)
 => {"warden.user.user.key"=>[["548814a064657654501a0000"], "$2a$10$73PE6lJ5iYxwumwZQ/qjjO"], "warden.user.user.session"=>{"unique_session_id"=>"AsqZJFimQjSEsYyAgL8T"}, "flash"=>{"discard"=>["notice"], "flashes"=>{"notice"=>"Je bent succesvol ingelogd."}}, "_csrf_token"=>"aOaum1ZeInfFvRgG8srczhiGnbpx41VIdix7+4QKxzo="} 

When i decode this in elixir i get: 

ExMarshal.decode(session.data) 
** (CaseClauseError) no case clause matching: "@"
    lib/ex_marshal/decoder.ex:10: ExMarshal.Decoder.decode_element/2
    lib/ex_marshal/decoder.ex:204: ExMarshal.Decoder.decode_hash/4
    lib/ex_marshal/decoder.ex:205: ExMarshal.Decoder.decode_hash/4
    lib/ex_marshal/decoder.ex:3: ExMarshal.Decoder.decode/1

Any idea how to solve this ?

**Comment by gaynetdinov** [comment]
Hello.

The reason of this failure is that ExMarshal does not support object references yet http://docs.ruby-lang.org/en/2.2.0/marshal_rdoc.html#label-Object+References

I will try to implement this type of encoding during this week.

**Comment by dewie** [comment]
Great thanks !

Met vriendelijke groet,

itXL
Daniel Wijnands

Tel: 0478-712016
Email: daniel@itxl.nl
Website: www.itxl.nl

**Comment by gaynetdinov** [comment]
Hello, @dewie.

Could you please try to decode rails session using `decode-references` branch?

**Comment by dewie** [comment]
Works great !

**Comment by gaynetdinov** [comment]
Cool! Please keep playing with this branch, if everything works ok, I will be more than happy to merge it in master and release new hex version on this weekend. Thanks.

**Comment by dewie** [comment]
As a learning experience i was trying it myself, but that would be a very long road ;)

**Comment by gaynetdinov** [comment]
I'd be very happy if you can describe how you were trying to decode rails session using ex_marshal. I'd like to put it to README to `Why?` section. Or you can create pull-request if you wish. Thanks.

**Comment by dewie** [comment]
No problem, but i'm afraid it isn't a standard rails setup. 
The sessions are stored in a mongodb database with mongoid (https://github.com/brianhempel/mongo_session_store)

The read a session in phoenix i only have to use the session id (stored in a cookie) 
And read the session with a ecto model: 

session = Myapp.Repo.get Myapp.Session, "session_id" 
data =  ExMarshal.decode(session.data)
%{"_csrf_token" => "Q1d0VNOfOtLSpLbpft/p9HpCPhlbECaw1Y3RmBsWxWY=",
  "warden.user.user.key" => [["548814a064657654501a0000"],
   "$2a$10$73PE6lJ5iYxwumwZQ/qjjO"],
  "warden.user.user.session" => %{"unique_session_id" => "yrqHE-H9-uapa-xTn7UC"}}

It works great !
